#!/bin/bash
# apply-wayland-flags.sh - Detect and fix fractional scaling issues
# in Electron/Chromium apps on Wayland
#
# Scans installed desktop files for Electron/Chromium apps and adds
# --disable-features=WaylandFractionalScaleV1 --ozone-platform-hint=wayland
# to their Exec lines via local overrides (~/.local/share/applications/).
#
# Also handles Flatpak apps via flatpak override --user --env.
#
# Usage:
#   apply-wayland-flags.sh          # incremental (new apps only)
#   apply-wayland-flags.sh --full   # full rescan (re-detect everything)

set -uo pipefail

VERSION="1"
MARKER="# Generated by apply-wayland-flags"
FLAGS="--disable-features=WaylandFractionalScaleV1 --ozone-platform-hint=wayland"
STATE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/apply-wayland-flags"
OVERRIDE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
RAW_BASE="https://raw.githubusercontent.com/ElMeGGa-14/apply-wayland-flags/main"
mkdir -p "$OVERRIDE_DIR" "$STATE_DIR"

# ── Known Electron/Chromium binary names ──────────────────────────
KNOWN_BINARIES=(
    google-chrome google-chrome-stable google-chrome-beta google-chrome-unstable
    chromium chromium-browser chromium-bsu
    brave brave-browser
    microsoft-edge microsoft-edge-dev microsoft-edge-beta
    vivaldi vivaldi-bin vivaldi-snapshot
    opera opera-beta opera-developer
    yandex-browser yandex-browser-beta
    arc-browser arc
    ungoogled-chromium ungoogled-chromium-bin
    iridium iridium-browser
    epic epic-browser
    slimjet slimjet-browser
    naver-whale whale whale-browser
    cent-browser cent
    code code-oss codium
    opencode-desktop opencode
    cursor
    antigravity antigravity-cli
    microsoft-teams teams teams-for-linux mattermost-desktop
    mongodb-compass figma-linux github-desktop
    gitkraken joplin typora marktext
    ferdium ferdi vesktop armcord
    threema session-desktop standard-notes
    electron
)

KNOWN_DESKTOP_PREFIXES=(
    discord slack whatsapp teams signal postman obsidian notion figma
    todoist spotify zoom insomnia anydesk teamviewer
    logseq zulip element keybase
    github-desktop gitkraken
    marktext typora joplin
    ferdium ferdi vesktop
    threema standard-notes
    mongodb-compass
    yandex-browser iridium-browser
    epic-browser slimjet
    naver-whale cent-browser
    arc-browser ungoogled-chromium
)

# ── Known Electron/Chromium Flatpak IDs ──────────────────────────
KNOWN_FLATPAK_IDS=(
    com.google.Chrome
    org.chromium.Chromium
    com.brave.Browser
    com.microsoft.Edge
    com.vivaldi.Vivaldi
    com.opera.Opera
    com.discordapp.Discord
    com.slack.Slack
    com.signal.Signal
    com.visualstudio.code
    com.visualstudio.code-oss
    md.obsidian.Obsidian
    rest.insomnia.Insomnia
    io.github.zen_browser.zen
    com.postman.Postman
)

# ── Detection ──────────────────────────────────────────────────────
is_electron_app() {
    local desktop_file="$1"
    local basename exec_line binary full_path

    basename=$(basename "$desktop_file" .desktop)
    exec_line=$(grep -m1 '^Exec=' "$desktop_file" 2>/dev/null || true)
    [[ -z "$exec_line" ]] && return 1

    binary=$(echo "$exec_line" | sed 's/^Exec=//' | awk '{print $1}' | xargs basename 2>/dev/null || true)
    full_path=$(echo "$exec_line" | sed 's/^Exec=//' | awk '{print $1}' 2>/dev/null || true)

    for b in "${KNOWN_BINARIES[@]}"; do
        [[ "$binary" == "$b" ]] && return 0
    done

    for prefix in "${KNOWN_DESKTOP_PREFIXES[@]}"; do
        [[ "$basename" == "$prefix" ]] && return 0
    done

    for b in "${KNOWN_BINARIES[@]}"; do
        [[ "$basename" == "$b" ]] && return 0
    done

    if echo "$full_path" | grep -qiE "(electron|chromium|chrome)"; then
        return 0
    fi

    if [[ ! "$full_path" == */* ]] && type -P "$full_path" &>/dev/null; then
        full_path=$(type -P "$full_path")
    fi

    if [[ -L "$full_path" ]]; then
        full_path=$(readlink -f "$full_path")
    fi

    if [[ -x "$full_path" ]] && file "$full_path" 2>/dev/null | grep -qi "ELF"; then
        if ldd "$full_path" 2>/dev/null | grep -qiE "(libelectron|libcef|libchrome)"; then
            return 0
        fi
        if strings "$full_path" 2>/dev/null | grep -qiE "(electron|chromium)"; then
            return 0
        fi
    fi

    return 1
}

# ── Desktop file patching ─────────────────────────────────────────
add_flags_to_exec() {
    local file="$1"
    local tmp=$(mktemp)

    while IFS= read -r line; do
        if [[ "$line" == Exec=* ]]; then
            if [[ "$line" != *"$FLAGS"* ]]; then
                local new_line
                if echo "$line" | grep -q '%[[:alpha:]%]'; then
                    new_line=$(echo "$line" | sed "s|\(%[[:alpha:]%]\)|$FLAGS \1|")
                else
                    new_line="Exec=$(echo "$line" | sed 's/^Exec=//') $FLAGS"
                fi
                echo "$new_line" >> "$tmp"
            else
                echo "$line" >> "$tmp"
            fi
        else
            echo "$line" >> "$tmp"
        fi
    done < "$file"

    echo "$MARKER" >> "$tmp"
    mv "$tmp" "$file"
    chmod 644 "$file"
}

# ── Flatpak handling ──────────────────────────────────────────────
handle_flatpak() {
    command -v flatpak &>/dev/null || return 0

    local flatpak_applied=0
    local flatpak_list

    flatpak_list=$(flatpak list --app --columns=application 2>/dev/null) || return 0

    for id in "${KNOWN_FLATPAK_IDS[@]}"; do
        if echo "$flatpak_list" | grep -qiF "$id"; then
            if echo "$id" | grep -qiE "(chrome|chromium|brave|edge|vivaldi|opera|yandex|iridium|slimjet|whale|cent|epic)"; then
                flatpak override --user --env=CHROME_FLAGS="$FLAGS" "$id" &>/dev/null
            fi
            flatpak override --user --env=ELECTRON_EXTRA_LAUNCH_ARGS="$FLAGS" "$id" &>/dev/null
            echo "  + flatpak: $id"
            ((flatpak_applied++))
        fi
    done

    flatpak override --user --env=ELECTRON_EXTRA_LAUNCH_ARGS="$FLAGS" &>/dev/null
    flatpak override --user --env=CHROME_FLAGS="$FLAGS" &>/dev/null
    echo "  + flatpak: global overrides set (ELECTRON_EXTRA_LAUNCH_ARGS + CHROME_FLAGS)"

    FLATPAK_RESULT=$((flatpak_applied + 1))
}

# ── Config file handling ──────────────────────────────────────────
# Some apps (notably google-chrome on Arch Linux) use a wrapper script
# that reads flags from $XDG_CONFIG_HOME/<app>-flags.conf.
# This ensures those config files also contain our Wayland flags.
handle_config_files() {
    local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
    local config_count=0

    for desktop_file in "$OVERRIDE_DIR"/*.desktop; do
        [[ -f "$desktop_file" ]] || continue
        grep -qF -e "$MARKER" "$desktop_file" 2>/dev/null || continue

        local exec_line binary_name
        exec_line=$(grep -m1 '^Exec=' "$desktop_file" 2>/dev/null || true)
        [[ -z "$exec_line" ]] && continue

        binary_name=$(echo "$exec_line" | sed 's/^Exec=//' | awk '{print $1}' | xargs basename 2>/dev/null || true)

        local conf_file=""
        case "$binary_name" in
            google-chrome*)       conf_file="chrome-flags.conf" ;;
            chromium*)            conf_file="chromium-flags.conf" ;;
            electron*)            conf_file="electron-flags.conf" ;;
            code|code-oss|codium) conf_file="code-flags.conf" ;;
        esac

        [[ -z "$conf_file" ]] && continue

        local conf_path="$config_dir/$conf_file"
        if [[ -f "$conf_path" ]] && ! grep -qF -- "--disable-features=WaylandFractionalScaleV1" "$conf_path" 2>/dev/null; then
            echo "# Added by apply-wayland-flags on $(date +%Y-%m-%d)" >> "$conf_path"
            echo "$FLAGS" >> "$conf_path"
            echo "  + config: $conf_file"
            ((config_count++))
        fi
    done

    CONFIG_COUNT=$config_count
}

FLATPAK_DESKTOP_DIRS=(
    /var/lib/flatpak/exports/share/applications
    "$HOME/.local/share/flatpak/exports/share/applications"
)

# ── Updates ────────────────────────────────────────────────────────
get_installed_version() {
    if [[ -f "$STATE_DIR/version" ]]; then
        cat "$STATE_DIR/version"
    else
        echo ""
    fi
}

get_remote_version() {
    curl -sSfL "https://api.github.com/repos/ElMeGGa-14/apply-wayland-flags/commits/main" 2>/dev/null | grep -m1 '"sha"' | cut -d'"' -f4 || echo ""
}

need_sudo_for_path() {
    local path="$1"
    local dir=$(dirname "$path")
    [[ ! -w "$dir" ]]
}

perform_update() {
    local script_target tui_target
    script_target=$(readlink -f "$0" 2>/dev/null || realpath "$0" 2>/dev/null || which "$0" 2>/dev/null)

    if need_sudo_for_path "$script_target"; then
        local SUDO="sudo"
    else
        local SUDO=""
    fi

    echo "Updating apply-wayland-flags..."
    local tmp_main=$(mktemp)
    if curl -sSfL "$RAW_BASE/apply-wayland-flags.sh" -o "$tmp_main" 2>/dev/null; then
        $SUDO cp "$tmp_main" "$script_target"
        $SUDO chmod +x "$script_target"
        echo "  + $(basename "$script_target") updated"
    else
        echo "  Error: could not download main script."
        rm -f "$tmp_main"
        return 1
    fi
    rm -f "$tmp_main"

    tui_target="$HOME/.local/bin/apply-wayland-flags-tui"
    if [[ -f "$tui_target" ]]; then
        local tmp_tui=$(mktemp)
        if curl -sSfL "$RAW_BASE/tui.sh" -o "$tmp_tui" 2>/dev/null; then
            cp "$tmp_tui" "$tui_target"
            chmod +x "$tui_target"
            echo "  + $(basename "$tui_target") updated"
        fi
        rm -f "$tmp_tui"
    fi

    local new_version
    new_version=$(get_remote_version)
    echo "$new_version" > "$STATE_DIR/version"
    echo "Update complete (version $new_version)."
}

check_for_updates() {
    local local_v remote_v
    local_v=$(get_installed_version)
    remote_v=$(get_remote_version)

    if [[ -z "$remote_v" ]] || [[ "$remote_v" == "$local_v" ]]; then
        return 0
    fi

    echo "Update available (new commit on GitHub)."
    echo "Run '$0 --update' to update."
    return 1
}

# ── Main ──────────────────────────────────────────────────────────
mode="incremental"
check_updates=true
while [[ $# -gt 0 ]]; do
    case "$1" in
        --full|-f) mode="full" ;;
        --check-update|-c) check_for_updates; exit $? ;;
        --update|-u) perform_update; exit $? ;;
        --no-check-update) check_updates=false ;;
        *) echo "Usage: $0 [--full|-f|--check-update|-c|--update|-u]" >&2; exit 1 ;;
    esac
    shift
done

if $check_updates; then
    check_for_updates
fi

if [[ "$mode" == "full" ]]; then
    for f in "$OVERRIDE_DIR"/*.desktop; do
        [[ -f "$f" ]] || continue
        case "$(basename "$f")" in
            apply-wayland-flags-tui.desktop) continue ;;
        esac
        if grep -qF -e "$MARKER" "$f" 2>/dev/null; then
            rm -f "$f"
        fi
    done
    echo "Full rescan: cleared overrides from previous runs."

    migrated=0
    for f in "$OVERRIDE_DIR"/*.desktop; do
        [[ -f "$f" ]] || continue
        case "$(basename "$f")" in
            apply-wayland-flags-tui.desktop) continue ;;
        esac
        if ! grep -qF -e "$MARKER" "$f" 2>/dev/null; then
            if grep -qF -e "$FLAGS" "$f" 2>/dev/null; then
                echo "$MARKER" >> "$f"
                echo "  ~ migrated: $(basename "$f")"
                ((migrated++))
            fi
        fi
    done
    if [[ "$migrated" -gt 0 ]]; then
        echo "Migrated: $migrated legacy override(s) to new tracking system."
    fi
fi

applied=0
flatpak_applied=0

for dir in /usr/share/applications "${FLATPAK_DESKTOP_DIRS[@]}"; do
    [[ -d "$dir" ]] || continue
    for desktop_file in "$dir"/*.desktop; do
    [[ -f "$desktop_file" ]] || continue
    name=$(basename "$desktop_file")
    override="$OVERRIDE_DIR/$name"

    [[ -f "$override" ]] && continue

    if is_electron_app "$desktop_file"; then
        cp "$desktop_file" "$override"
        add_flags_to_exec "$override"
        echo "  + $name"
        ((applied++))
    fi
    done
done

CONFIG_COUNT=0
handle_config_files

FLATPAK_RESULT=0
handle_flatpak
flatpak_count=$FLATPAK_RESULT

if [[ "$applied" -eq 0 ]] && [[ "$flatpak_count" -eq 0 ]] && [[ "$CONFIG_COUNT" -eq 0 ]]; then
    echo "No Electron/Chromium apps found."
else
    local parts=""
    [[ "$applied" -gt 0 ]] && parts+="$applied desktop file(s), "
    [[ "$flatpak_count" -gt 0 ]] && parts+="$flatpak_count flatpak override(s), "
    [[ "$CONFIG_COUNT" -gt 0 ]] && parts+="$CONFIG_COUNT config file(s), "
    parts="${parts%, }"
    echo "Applied: $parts."
fi
